name: Deploy Lab 2 to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'lab-2/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './lab-2'    # Просто загружаем всю папку lab-2
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4